repos:
-   repo: https://github.com/thlorenz/doctoc
    rev: v1.4.0
    hooks:
    -   id: doctoc
        args: [".", '--title=## Table of Contents', "--github"]
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
      files: ^src/